baseURL = "https://allocsoc.net/"
languageCode = "en-us"
title = "KZK's blog"
theme = "mini"

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=10 # articles per page

[permalinks]
posts = "/posts/:title/"

[markup.highlight]
guessSyntax = true
style = "emacs"

[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 2

[markup.goldmark.renderer]
unsafe = true


[social]
github = "https://github.com/kozko2001"
twitter = "https://twitter.com/kozko2001"

[params]
author = "Jordi Coscolla"
bio = "Lead engineer"
description = "KZK's blog"
enableRSS = true
enableComments = false
enableGoogleAnalytics = true
showToc = true
showPowerBy = true
math = true
hiddenPostSummaryInHomePage = false


[[params.links]]
name = "CV"
path = "https://google.com"

    ## e.g.
    # - name: Project
    #   path: /project

googleAnalytics = "UA-30847907-1"
