apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

# Optional: Add common labels to all resources

# Optional: Namespace for all resources (can be overridden by FluxCD)
namespace: blog
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: blog
    app.kubernetes.io/version: 1.0.0
