name: DockerImage

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: harbor.allocsoc.net
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.100.1'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Build, tag, and push image to Harbor
        env:
          HARBOR_REGISTRY: harbor.allocsoc.net
          REPOSITORY: blog
          IMAGE_TAG: prod
        run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          docker build -t $HARBOR_REGISTRY/$REPOSITORY:$git_hash .
          docker push $HARBOR_REGISTRY/$REPOSITORY:$git_hash
      - name: get config
        shell: bash
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        run: |
          git config --global user.email "kozko2001@gmail.com"
          git config --global user.name "kozko2001"
          git clone "https://$API_TOKEN_GITHUB@github.com/kozko2001/k8s-config.git" "k8s-config"

      - name: update version
        shell: bash
        run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          sed -i "s/.*097742747651.dkr.ecr.eu-west-1.amazonaws.com\/blog:.*/        image: 097742747651.dkr.ecr.eu-west-1.amazonaws.com\/blog:$git_hash/" k8s-config/blog/service.yml
      - name: push config
        shell: bash
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        run: |
          git -C k8s-config add .
          git -C k8s-config status

          git -C k8s-config commit  -m "updated blog version"
          git -C k8s-config push
